# Generated by Django 3.2.9 on 2021-11-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
