# Generated by Django 3.2.9 on 2021-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True, verbose_name='ID фильма')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('imdb_rating', models.FloatField(verbose_name='Рейтинг фильма')),
                ('genre', models.TextField(verbose_name='Жанры')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('writers_names', models.TextField(verbose_name='Имя сценариста')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('actors_names', models.TextField(verbose_name='Список имен, разделенных запятыми')),
                ('actors', models.ManyToManyField(blank=True, to='hollywood.Actor', verbose_name='ID актера')),
                ('writers', models.ManyToManyField(blank=True, to='hollywood.Writer', verbose_name='ID сценариста')),
            ],
        ),
    ]
