# Generated by Django 3.2.9 on 2021-11-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=200, null=True, verbose_name='ID сценариста'),
        ),
    ]
