# Generated by Django 3.2.9 on 2021-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0004_movie_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_id',
            field=models.IntegerField(verbose_name='ID актера'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(verbose_name='ID фильма'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.IntegerField(verbose_name='ID сценариста'),
        ),
    ]
