# Generated by Django 3.2.9 on 2021-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0005_auto_20211110_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=200, verbose_name='ID фильма'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer_id',
            field=models.CharField(max_length=200, verbose_name='ID сценариста'),
        ),
    ]
