# Generated by Django 3.2.9 on 2021-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0006_auto_20211110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя сценариста'),
        ),
    ]
